"""add audit_logs

Revision ID: c6d52c73c44c
Revises: 9cf6e6460bc9
Create Date: 2026-02-12 01:02:27.264322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6d52c73c44c'
down_revision = '9cf6e6460bc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_index('ix_audit_log_id', table_name='audit_log')
    op.drop_index('ix_audit_log_role', table_name='audit_log')
    op.drop_index('ix_audit_log_station_id', table_name='audit_log')
    op.drop_index('ix_audit_log_ticket_id', table_name='audit_log')
    op.drop_index('ix_audit_log_user_id', table_name='audit_log')
    op.drop_index('ix_audit_log_username', table_name='audit_log')
    op.drop_table('audit_log')
    op.alter_column('pumps', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_pumps_fuel_type'), 'pumps', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_pumps_id'), 'pumps', ['id'], unique=False)
    op.create_index(op.f('ix_pumps_station_id'), 'pumps', ['station_id'], unique=False)
    op.alter_column('queue_tickets', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_queue_tickets_driver_user_id'), 'queue_tickets', ['driver_user_id'], unique=False)
    op.create_index(op.f('ix_queue_tickets_fuel_type'), 'queue_tickets', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_queue_tickets_id'), 'queue_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_queue_tickets_station_id'), 'queue_tickets', ['station_id'], unique=False)
    op.create_index(op.f('ix_queue_tickets_status'), 'queue_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_queue_tickets_ticket_no'), 'queue_tickets', ['ticket_no'], unique=False)
    op.drop_column('queue_tickets', 'post_no')
    op.alter_column('ratings', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_ratings_driver_user_id'), 'ratings', ['driver_user_id'], unique=False)
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_station_id'), 'ratings', ['station_id'], unique=False)
    op.alter_column('reservations', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_reservations_driver_user_id'), 'reservations', ['driver_user_id'], unique=False)
    op.create_index(op.f('ix_reservations_end_time'), 'reservations', ['end_time'], unique=False)
    op.create_index(op.f('ix_reservations_fuel_type'), 'reservations', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_index(op.f('ix_reservations_start_time'), 'reservations', ['start_time'], unique=False)
    op.create_index(op.f('ix_reservations_station_id'), 'reservations', ['station_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_index(op.f('ix_stations_latitude'), 'stations', ['latitude'], unique=False)
    op.create_index(op.f('ix_stations_longitude'), 'stations', ['longitude'], unique=False)
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_index(op.f('ix_stations_longitude'), table_name='stations')
    op.drop_index(op.f('ix_stations_latitude'), table_name='stations')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_station_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_start_time'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_fuel_type'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_end_time'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_driver_user_id'), table_name='reservations')
    op.alter_column('reservations', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_ratings_station_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_driver_user_id'), table_name='ratings')
    op.alter_column('ratings', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('queue_tickets', sa.Column('post_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_queue_tickets_ticket_no'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_status'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_station_id'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_id'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_fuel_type'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_driver_user_id'), table_name='queue_tickets')
    op.alter_column('queue_tickets', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_pumps_station_id'), table_name='pumps')
    op.drop_index(op.f('ix_pumps_id'), table_name='pumps')
    op.drop_index(op.f('ix_pumps_fuel_type'), table_name='pumps')
    op.alter_column('pumps', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('entity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_log_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='audit_log_pkey')
    )
    op.create_index('ix_audit_log_username', 'audit_log', ['username'], unique=False)
    op.create_index('ix_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_index('ix_audit_log_ticket_id', 'audit_log', ['ticket_id'], unique=False)
    op.create_index('ix_audit_log_station_id', 'audit_log', ['station_id'], unique=False)
    op.create_index('ix_audit_log_role', 'audit_log', ['role'], unique=False)
    op.create_index('ix_audit_log_id', 'audit_log', ['id'], unique=False)
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    # ### end Alembic commands ###
